import {Modifier} from './Modifier'

export type ExoStoreData = {
	name: string,
	portType: number[],
	ceConsumption: number,
	ceConsumptionRate: number,
	ceConsumptionUnit: string,
	price: number,
	description: string,
	mods: Modifier[],
}

export class ExoStore {
	static items: ExoStoreData[] = [{
		name: "Acumulador de CE",
		portType: [1, 5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 50,
		description: "Acumula una reserva energética de emergencia de 50 CE.",
		mods: [{
			name: "Acumula 50 CE",
			type: "",
		}],
	}, {
		name: "Acumulador de CE avanzado",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 200,
		description: "Acumula una reserva energética de250 CE.",
		mods: [{
			name: "Acumula 250 CE",
			type: "",
		}],
	}, {
		name: "Análisis de degradación atómica",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 350,
		description: "Controla un dron con un equipo completo de análisis que puede tomar y contener pequeñas muestras de material radioactivo.",
		mods: [{
			name: "Dron análisis",
			type: "narrative",
		}],
	}, {
		name: "Artillero",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 700,
		description: "Permite manipular dos cañones de la nave a la vez. Multiplica el daño de Ataque por dos.",
		mods: [{
			name: "2 cañones nave",
			type: "",
		}, {
			name: "Usar 2 cañones nave",
			type: "",
		}],
	}, {
		name: "Artillero profesional",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 40,
		description: "Permite manipular hasta cinco cañones de la nave a la vez. Multiplica el daño de Ataque por cinco.",
		mods: [{
			name: "Usar 5 cañones nave",
			type: "",
		}],
	}, {
		name: "Brazos de combate",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 40,
		description: "Son dos brazos acoplados al robotta que al activarse ofrecen una acción extra de combate en Ataque a distancia o Ataque directo.",
		mods: [{
			name: "Acción combate extra",
			type: "",
		}],
	}, {
		name: "Cañon láser",
		portType: [2],
		ceConsumption: 3,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 300,
		description: "Un cañón láser acoplado al cuerpo.",
		mods: [{
			name: "Cañon láser",
			type: "",
		}],
	}, {
		name: "Cuchilla de energia",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 40,
		description: "Crea una cuchilla de energía que suma +3 a Ataque directo.",
		mods: [{
			name: "+3 Ataque directo",
			type: "attribute",
		}],
	}, {
		name: "Dermoestética",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 20,
		description: "Personaliza la cubierta del robotta con los colores, diseños y estilos deseados.",
		mods: [{
			name: "Personalización cubierta robotta",
			type: "narrative",
		}],
	}, {
		name: "Drenaje",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 140,
		description: "Drena CE de otro robotta a un ritmo de10CE/1h. Requiere la conexión de un Exo gemelo a dicho robotta.",
		mods: [{
			name: "Drenaje",
			type: "narrative",
		}],
	}, {
		name: "Drenaje de systemas",
		portType: [6],
		ceConsumption: 1,
		ceConsumptionRate: 10,
		ceConsumptionUnit: "t",
		price: 200,
		description: "Un tecnomante puede usar este Exo para drenar 1CE/t a cada robotta que se encuentre en un área de 10 m. El robotta drenado se da cuenta de la pérdida al momento, pero no tiene forma de percibir quién lo provoca. Si quien lo usa no es un tecnomante, debe hacer una tirada; con un resultado par puede usar el Exo, con uno impar no.",
		mods: [{
			name: "Drenaje area",
			type: "narrative",
		}],
	}, {
		name: "Dron Médico",
		portType: [5],
		ceConsumption: 2,
		ceConsumptionRate: 10,
		ceConsumptionUnit: "t",
		price: 220,
		description: "Es una esfera que se mantiene levitando a la espera de que su robotta necesite algún tipo de cuidado médico. Restaura hasta 35 SV.",
		mods: [{
			name: "Restaura hasta 35 SV.",
			type: "narrative",
		}],
	}, {
		name: "Encriptador de comunicación",
		portType: [4],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 20,
		description: "Crea canales seguros de comunicación entre otros robotta con el mismo Exo. Si el receptor no tiene el mismo Exo, solo se inhibe la localización del emisor. Para hackearlo hay que superar una dificultad de 17.",
		mods: [{
			name: "Comunicación segura",
			type: "narrative",
		}],
	}, {
		name: "Escudo de energía en arma",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 5,
		ceConsumptionUnit: "t",
		price: 40,
		description: "Polígonos de energía que se forman en el cañón del arma. Ofrece +1 a Defensa.",
		mods: [{
			name: "+1 Defensa",
			type: "attribute",
		}],
	}, {
		name: "Escudo de energía esférica",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 4,
		ceConsumptionUnit: "t",
		price: 30,
		description: "Crea un escudo de energía con forma de lentilla compuesto por láminas hexagonales que flota ante el robotta. El escudo aporta +2 a Defensa.",
		mods: [{
			name: "+2 Defensa",
			type: "attribute",
		}],
	}, {
		name: "Escudo de energía orbital",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 150,
		description: "Es un pequeño escudo de energía de 20 cm que se interpone entre la amenaza y el robotta. Tiene Absorción 30.",
		mods: [{
			name: "Escudo de absorción 30",
			type: "",
		}],
	}, {
		name: "Espada cuántica",
		portType: [6],
		ceConsumption: 2,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 900,
		description: "Materializa una espada de nanoacero en la mano del robotta. Otorga +2 a iniciativa, +3 a Ataque directo y +1 a Carisma.",
		mods: [{
			name: "+2 Iniciativa",
			type: "attribute",
		}, {
			name: "+3 Ataque directo",
			type: "attribute",
		}, {
			name: "+1 Carisma",
			type: "attribute",
		}],
	}, {
		name: "Exo cuántico de fuego",
		portType: [6],
		ceConsumption: 1,
		ceConsumptionRate: 10,
		ceConsumptionUnit: "t",
		price: 1200,
		description: "Recubre al robotta de una capa de plasma solar con aspecto etéreo. Otorga +2 a Carisma, +2 a Percepción y +5 al daño por contacto.",
		mods: [{
			name: "+2 Carisma",
			type: "attribute",
		}, {
			name: "+2 Percepción",
			type: "attribute",
		}, {
			name: "+2 Daño por contacto",
			type: "narrative",
		}],
	}, {
		name: "Flujo",
		portType: [4, 5],
		ceConsumption: 3,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 25,
		description: "Permite que el robotta entre en el Gran Flujo y tenga visiones y sueños aleatorios.",
		mods: [{
			name: "Entrada al flujo",
			type: "narrative",
		}],
	}, {
		name: "Geoposicionamiento de flujo",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 20,
		description: "Gracias a este Exo, un robotta siempre sabe dónde están los puntos cardinales y en qué coordenadas y profundidad se encuentra en todo momento, sea dentro de una nave o en los recovecos de una cueva.",
		mods: [{
			name: "Orientación por flujo",
			type: "narrative",
		}],
	}, {
		name: "Hackeo básico",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 45,
		description: "Suma +3 a la dificultad de hackear cualquier aparato que el robotta esté usando.",
		mods: [{
			name: "+3 contra hackeo",
			type: "narrative",
		}],
	}, {
		name: "Infobox",
		portType: [4],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 20,
		description: "Encierra una gran cantidad de información codificada a la que nadie, ni siquiera el propio robotta, puede acceder sin introducir la clave. Para hackearlo hay que superar una dificultad de 21.",
		mods: [{
			name: "Infobox",
			type: "narrative",
		}],
	}, {
		name: "Kamikaze",
		portType: [2],
		ceConsumption: 4,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 400,
		description: "Crea una explosión atroz que devasta todo en un área de 40 m con 300 puntos de daño.",
		mods: [{
			name: "Autodestrucción",
			type: "narrative",
		}],
	}, {
		name: "Kit mecánico",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 250,
		description: "Controla un dron automatizado que permite la reparación de maquinaria en general. Con este kit se pueden eliminar hasta dos estados negativos en una nave.",
		mods: [{
			name: "Reparar maquinária",
			type: "narrative",
		}],
	}, {
		name: "Kit profesión básico",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 20,
		description: "Ofrece una estructura de apoyo para tareas de alguna profesión específica. Son más grandes y abundantes que los kits avanzados. Otorgan +2 a la Profesión asociada.",
		mods: [{
			name: "+2 Profesión asociada",
			type: "",
		}],
	}, {
		name: "Kit profesión avanzado",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 60,
		description: "Ofrece una estructura de apoyo para tareas de una profesión específica. Son más escasos y mejor diseñados que los kits básicos. Otorgan +4 a la Profesión asociada.",
		mods: [{
			name: "+4 profesión asociada",
			type: "",
		}],
	}, {
		name: "Mejora básica de arma",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 5,
		ceConsumptionUnit: "t",
		price: 70,
		description: "Ofrece +1 a Ataque a distancia o a Ataque directo.",
		mods: [{
			name: "+1 Ataque distancia o directo",
			type: "",
		}],
	}, {
		name: "Mejora de blindaje",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 10,
		ceConsumptionUnit: "t",
		price: 65,
		description: "Aumenta la estructura del robotta con un nanomaterial que aporta +2 a Defensa.",
		mods: [{
			name: "+2 a Defensa",
			type: "attribute",
		}],
	}, {
		name: "Pistola láser",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 80,
		description: "Un cañón acoplado en el cuerpo del robotta. Se comporta como una pistola láser.",
		mods: [{
			name: "Pistola láser adicional",
			type: "narrative",
		}],
	}, {
		name: "Placa solar",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 60,
		description: "Permite captar energía del sol a un ritmo de 1 CE por cada hora de exposición directa.",
		mods: [{
			name: "Capta 1 CE/h",
			type: "narrative",
		}],
	}, {
		name: "Realidad aumentada comercial",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 30,
		description: "Uno de los Exos más vendidos en el mundo. Ofrece un mapa en realidad aumentada dentro de numerosas ciudades, con la ubicación de sus comercios y tiendas, así como ofertas de todo tipo que tan solo se pueden apreciar gracias a él.",
		mods: [{
			name: "Realidad aumentada comercial",
			type: "narrative",
		}],
	}, {
		name: "Realidad aumentada de red",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "d",
		price: 40,
		description: "Con este Exo, una tripulación o un grupo de robotta pueden coordinar su realidad aumentada para percibir todos el mismo entorno. Hay múltiples diseños: bosques, playas tropicales...",
		mods: [{
			name: "Realidad aumentada de red",
			type: "narrative",
		}],
	}, {
		name: "Recuperador de colapso energético",
		portType: [5],
		ceConsumption: 100,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 1200,
		description: "Aplica una descarga de 100 CE para que salga del estado de colapso energético a un robotta, que recupera 10 CE.",
		mods: [{
			name: "Recuperador de colapso energético",
			type: "manual",
		}],
	}, {
		name: "Recuperador del Gran Flujo",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 3500,
		description: "Permite que el robotta, en caso de encontrar la muerte, la afronte con una modificación beneficiosa: el jugador tira 4 dados en lugar de 3.",
		mods: [{
			name: "4 dados tras la muerte",
			type: "manual",
		}],
	}, {
		name: "Replicante",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 10,
		ceConsumptionUnit: "t",
		price: 250,
		description: "Crea un doble del robotta con la mitad de sus valores de Características. Si recibe daño, se desvanece. Puede alejarse a 200 m del robotta que lo genera. El robotta que lo maneja reduce su Cálculo a la mitad mientras lo usa.",
		mods: [{
			name: "Replicante",
			type: "manual",
		}, {
			name: "Calculo/2",
			type: "attribute",
		}],
	}, {
		name: "Retroproyector",
		portType: [3],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 35,
		description: "Permite al robotta desplazarse volando con turbinas acopladas a su cuerpo. Puede ser una única estructura o un conjunto de tres discretas turbinas.",
		mods: [{
			name: "Retroproyector",
			type: "narrative",
		}],
	}, {
		name: "Rifle láser retráctil",
		portType: [2],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 200,
		description: "Un rifle láser que se esconde en la espalda, el hombro o el pecho.",
		mods: [{
			name: "Rifle láser adicional",
			type: "manual",
		}],
	}, {
		name: "Satélite orbital básico",
		portType: [4],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 80,
		description: "Lanza un pequeño dron con forma esférica que proyecta los sentidos del robotta y le permite percibir y emitir señales de onda y triangular posiciones hasta a 50 km de distancia.",
		mods: [{
			name: "Satélite orbital",
			type: "narrative",
		}],
	}, {
		name: "Seguridad de Dáemyr",
		portType: [6],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 45000,
		description: "Hace una copia de seguridad del Dáemyr del robotta en el propio Exo, y solo se completa si detecta la muerte del cuerpo. Este Exo se considera contenedor del Dáemyr del robotta, por lo que se podría volcar en otro cuerpo válido. Con este Exo no se hace tirada de muerte.",
		mods: [{
			name: "Seguridad de Dáemyr",
			type: "narrative",
		}],
	}, {
		name: "Sensor de cuantificación",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 250,
		description: "Permite conocer los valores de Características del robotta objetivo. Requiere de una tirada de Cálculo con dificultad 14. La distancia máxima para percibir es de 10 m.",
		mods: [{
			name: "Sensor de cuantificación",
			type: "manual",
		}],
	}, {
		name: "Sensor de identificación de Exo",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 120,
		description: "Permite ver el tipo y número de Exos del robotta objetivo. Requiere una tirada de Cálculo con dificultad 12. La distancia máxima para percibir es de 100 m.",
		mods: [{
			name: "Identificar Exo",
			type: "manual",
		}],
	}, {
		name: "Silencio de sensor",
		portType: [1],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "h",
		price: 40,
		description: "Hace que el robotta no pueda ser captado por dos sentidos.",
		mods: [{
			name: "Silencio de sensor",
			type: "narrative",
		}],
	}, {
		name: "Soporte Vital",
		portType: [5],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 40,
		description: "Aporta una reserva extra de 30 SV.",
		mods: [{
			name: "+30 SV",
			type: "attribute",
		}],
	}, {
		name: "Soporte Vital avanzado",
		portType: [5],
		ceConsumption: 2,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 150,
		description: "Aporta una reserva extra de 70 SV.",
		mods: [{
			name: "+70 SV",
			type: "attribute",
		}],
	}, {
		name: "Sueño cuántico",
		portType: [6],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 350,
		description: "Un tecnomante puede entrar en el Gran Flujo para tener visiones de la Singularidad. Si quien lo usa no es un tecnomante, debe hacer una tirada; con un resultado par ve retazos de la Singularidad, con uno impar no puede usar el Exo.",
		mods: [{
			name: "Sueño cuántico",
			type: "narrative",
		}],
	}, {
		name: "Sueño superficial",
		portType: [4],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 40,
		description: "Permite al robotta entrar en el Gran Flujo para obtener energía electromagnética de emergencia. El ritmo de recarga es de 2 CE por cada hora de sueño.",
		mods: [{
			name: "Recarga 2CE/h",
			type: "manual",
		}],
	}, {
		name: "Sueño profundo",
		portType: [4],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "u",
		price: 250,
		description: "Permite al robotta entrar en el Gran Flujo para obtener una descarga especialmente veloz de CE en sus sistemas. El ritmo de recarga es de hasta 15 CE por cada hora de sueño.",
		mods: [{
			name: "Recarga 15CE/h",
			type: "manual",
		}],
	}, {
		name: "Supresor de consecuencias de salud",
		portType: [1],
		ceConsumption: 10,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 100,
		description: "Permite al robotta eliminar una consecuencia de salud cada 3 horas.",
		mods: [{
			name: "Eliminar consecuencia",
			type: "manual",
		}],
	}, {
		name: "Traslado cuántico",
		portType: [6],
		ceConsumption: 1,
		ceConsumptionRate: 1,
		ceConsumptionUnit: "t",
		price: 350,
		description: "Un tecnomante puede desatomizarse y reconfigurarse de inmediato en unárea de 5 m por cada CE que gaste durante el traslado. Si quien lo usa no es un tecnomante, debe hacer una tirada; con un resultado par puede usar el Exo, con uno impar no. Un resultado de1 supone una fusión con otro material.",
		mods: [{
			name: "Traslado cuántico",
			type: "manual",
		}],
	}];

	static getItem(id: string): ExoStoreData {
		const item = ExoStore.items.filter(item => item.name === id);
		return item[0];
	}
}
